config/routes.rb
ConvertOfficeDemo::Application.routes.draw do
  resources :assets do
    member do
      get 'convert_document'
      get 'download_document'
      get 'delete_document'
    end
  end

  devise_for :users
  root :to => "home#index"

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :user
  has_many :asset_documents,:dependent => :destroy
  has_attached_file :attachment, :path=>":rails_root/public/attachments/:id/:styles.:basename.:extension",
                    :url => "/attachments/:id/:styles.:basename.:extension"
  validates_attachment_presence :attachment
  validates_attachment_content_type :attachment,
                                    :content_type => ['application/vnd.ms-powerpoint', 'application/vnd.ms-excel', 'application/msword', 'application/vnd.oasis.opendocument.text','application/rtf','text/html']
  TEXT_FORMAT = %w(pdf odt sxw rtf  doc txt html wiki)
  XL_FORMAT = %w(pdf ods sxc xls csv tsv html)
  PT_FORMAT = %w(pdf swf odp sxi ppt html)
  ODG_FORMAT = %w(svg swf)
  VALID_FORMAT=	{
      "odt"=>TEXT_FORMAT,
      "sxw"=>TEXT_FORMAT,
      "rtf"=>TEXT_FORMAT,
      "doc"=>TEXT_FORMAT,
      "wpd"=>TEXT_FORMAT,
      "txt"=>TEXT_FORMAT,
      "html"=>TEXT_FORMAT,
      "htm"=>TEXT_FORMAT,
      "ods"=>XL_FORMAT,
      "sxc"=>XL_FORMAT,
      "xls"=>XL_FORMAT,
      "csv"=>XL_FORMAT,
      "tsv"=>XL_FORMAT,
      "odp"=>PT_FORMAT,
      "sxi"=>PT_FORMAT,
      "ppt"=>PT_FORMAT,
      "odg"=>ODG_FORMAT
  }
  def list_valid_formats

    file_ext_name = File.extname(self.attachment_file_name).split(".").last
    if VALID_FORMAT.keys.include?(file_ext_name)
      VALID_FORMAT[file_ext_name]
    else
      []
    end
  end

  def start_conversion(format)
    src_file = self.attachment.path
    dest_file= self.attachment.path+"."+format
     ConvertOffice::ConvertOfficeFormat.new.convert(src_file,dest_file)
    [self.attachment_file_name+"."+format,self.attachment.url.split("?").first+"."+format]
  end
end

app/models/asset_document.rb
class AssetDocument < ActiveRecord::Base
  belongs_to :asset
  before_destroy :delete_necessary_document

  def delete_necessary_document
    debugger
    if File.exist?("#{Rails.root}/public#{self.path}")
      FileUtils.rm("#{Rails.root}/public#{self.path}")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :assets,:dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  # GET /assets
  # GET /assets.xml
  before_filter :load_user
  def index
    @assets = @user.assets

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @assets }
    end
  end

  # GET /assets/1
  # GET /assets/1.xml
  def show
    @asset = @user.assets.find(params[:id])
    @valid_formats = @asset.list_valid_formats
    @asset_documents = @asset.asset_documents

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @asset }
    end
  end

  # GET /assets/new
  # GET /assets/new.xml
  def new
    @asset =@user.assets.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @asset }
    end
  end

  # GET /assets/1/edit
  def edit
    @asset = @user.assets.find(params[:id])
  end

  # POST /assets
  # POST /assets.xml
  def create
    @asset = @user.assets.new(params[:asset])
    respond_to do |format|
      if @asset.save
        format.html { redirect_to(@asset, :notice => 'Asset was successfully created.') }
        format.xml  { render :xml => @asset, :status => :created, :location => @asset }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /assets/1
  # PUT /assets/1.xml
  def update
    @asset = @user.assets.find(params[:id])

    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.html { redirect_to(@asset, :notice => 'Asset was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.xml
  def destroy
    @asset = @user.assets.find(params[:id])
    @asset.destroy

    respond_to do |format|
      format.html { redirect_to assets_url }
      format.xml  { head :ok }
    end
  end

  def convert_document

    @asset = @user.assets.find(params[:id])
    file_name,path = @asset.start_conversion(params[:valid_format])
    @asset.asset_documents.create(:name=>file_name,:path=>path)
    respond_to do |format|
      format.html { redirect_to(@asset, :notice => 'Document was successfully converted.') }
    end
  end

  def download_document
    @asset = @user.assets.find(params[:id])
    @asset_document = @asset.asset_documents.find(params[:asset_document_id])
    if !@asset_document.blank?
      send_file("#{Rails.root}/public#{@asset_document.path}")
    end
  end
  def delete_document
    @asset = @user.assets.find(params[:id])
    @asset_document = @asset.asset_documents.find(params[:asset_document_id])
    if !@asset_document.blank?
      @asset_document.destroy
    end
    respond_to do |format|
      format.html { redirect_to(@asset,:notice => "Document is successfully deleted") }

    end
  end
  private
  def load_user
    @user = current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def clearing_span
    content_tag(:span, '', :class => 'clear')
  end
  def title(text)
    content_tag(:h1,text,:class=>'page-title')
  end
  # Returns true if sidebar disabled for current page/controller
  def sidebar_enabled?
    current_page = "#{controller.controller_name}.#{controller.action_name}"
    current_controller = controller.controller_name
    pages = %w(report_templates.new report_templates.edit )

    return pages.include?(current_page) || pages.include?(current_controller)
  end
  def main_content_css_class
    sidebar_enabled? ? "grid_12" : "grid_16"
  end

  # Returns the CSS class for the 'sidebar' div depending on sidebar requirement
  def sidebar_css_class
    sidebar_enabled? ? "grid_4" : "dont-show"
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/assets/_form.html.erb
<%= form_for(@asset,:html=>{:class=>'data-form',:multipart => true }) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.file_field :attachment %>
  </div>
    
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assets/edit.html.erb
<h1>Editing asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb
<h1>Listing assets</h1>
<div class="listing">
  <table>
    <tr>
      <th>Name</th>
      <th width="30"></th>

    </tr>

    <% @assets.each do |asset| %>
        <tr>
          <td><%= link_to asset.name,asset %></td>
          <td><%=  link_to image_tag("delete_10.png"), asset, :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
    <% end %>
  </table>
</div>
<br />

<%= link_to 'New Asset', new_asset_path %>

app/views/assets/new.html.erb
<h1>New asset</h1>

<%= render 'form' %>

<%= link_to 'Back', assets_path %>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>
<p>

  <% form_tag(convert_document_asset_path(@asset),:method=>:get) do %>
     Convert Into <%= select_tag :valid_format, options_for_select(@valid_formats)%>
    <%= submit_tag "Convert" %>  
  <% end  %>
</p>

<p>
  <b>Name:</b>
  <%= @asset.name %>
</p>
<br />
<p>
  <b>File Name</b>
  <%=link_to @asset.attachment_file_name,@asset.attachment.url %>
</p>
<br />


<div class="listing">
  <table>
    <tr>
        <th>Name</th>
        <th width="200">Download</th>
        <th width="30"></th>
    </tr>
    <% @asset_documents.each do |asset_document| %>
    <tr>
      <td><%= asset_document.name %></td>
      <td><%=link_to "Download",download_document_asset_path(@asset,:asset_document_id=>asset_document.id) %></td>
      <td><%=link_to image_tag('delete_10.png'),delete_document_asset_path(@asset,:asset_document_id=>asset_document.id) %></td>
    </tr>
    <% end %>    
  </table>

</div>
<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'reset','grid','application'%>
  <%= javascript_include_tag :defaults %>
  <title>Office Conversion  <%=raw ((yield(:title) || "Untitled")) %></title>
  <%= yield :head %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="container_16 every-thing">

  <div class="header">
    <div class="grid_16">
      <div class="grid_8" >
        <div class="login-bar-left"><h1>Convert Various Office format to another format</h1></div>
      </div>
      <div class="grid_8">
        <div id="login-bar-right">
          <ul>
            <% if !current_user.blank? %>
                <li><%= link_to "Logout",  destroy_user_session_path%></li>
                <li><%=link_to "Profile | ", edit_user_registration_path %> </li>

            <% else %>
                <li><%= link_to "Register ", new_user_registration_path %></li>
                <li><%= link_to "Login | ", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <%= clearing_span %>
    <div class="main-nav">
      <ul>
        <% if current_user.blank? %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Register ", new_user_registration_path %></li>
        <% else %>
            <li><%= link_to "Home", root_url, :method => :delete %></li>
            <li><%= link_to "Asset",assets_path %></li>

        <% end %>

      </ul>
    </div>
  </div>
  <%= clearing_span %>
  <div id="wrapper">
    <div id="content" class="<%= main_content_css_class %>">
      <%= title  yield :title %>
      <%= yield %>
    </div>
    <div class="<%=  sidebar_css_class %>">
      <%=yield :sidebar %>
    </div>
    <%= clearing_span %>
  </div>

  <div class="push"></div>

</div>



<div class="container_16">

  <div id="footer">
    <p class="copyright">&copy; 2010 <a href="http://raistech.com">Amar Daxini</a></p>
  </div>
  <%= yield :javascripts %>

</div>
</body>
</html>